SONGS = [
    {
        "id": 1,
        "title": "See You Again",
        "artist": "Wiz Khalifa ft. Charlie Puth",
        "genre": "hip-hop",
        "description": "Bài hát về tình bạn, chia tay và kỷ niệm với người đã ra đi.",
    },
    {
        "id": 2,
        "title": "Shape of You",
        "artist": "Ed Sheeran",
        "genre": "pop",
        "description": "Bài pop sôi động về tình yêu và sự hấp dẫn thể chất.",
    },
    {
        "id": 3,
        "title": "Someone Like You",
        "artist": "Adele",
        "genre": "ballad",
        "description": "Ballad buồn về tình yêu đã mất. Người hát gặp lại người yêu cũ.",
    },
    {
        "id": 4,
        "title": "Nơi Này Có Anh",
        "artist": "Sơn Tùng M-TP",
        "genre": "v-pop",
        "description": "Bài hát tình yêu ngọt ngào tiếng Việt. Kể về việc mang người yêu về quê.",
    },
    {
        "id": 5,
        "title": "Em Của Ngày Hôm Qua",
        "artist": "Sơn Tùng M-TP",
        "genre": "v-pop",
        "description": "Bài hát về nỗi nhớ người yêu cũ và cảm giác hối tiếc.",
    },
    {
        "id": 6,
        "title": "Bohemian Rhapsody",
        "artist": "Queen",
        "genre": "rock",
        "description": "Bản rock opera huyền thoại kể câu chuyện về một người đã phạm tội.",
    },
    {
        "id": 7,
        "title": "Happy",
        "artist": "Pharrell Williams",
        "genre": "pop",
        "description": "Bài hát vui vẻ, lạc quan khuyến khích mọi người vui lên.",
    },
    {
        "id": 8,
        "title": "Fix You",
        "artist": "Coldplay",
        "genre": "alternative",
        "description": "Bài hát an ủi về việc chữa lành nỗi đau.",
    },
    {
        "id": 9,
        "title": "Despacito",
        "artist": "Luis Fonsi ft. Daddy Yankee",
        "genre": "reggaeton",
        "description": "Bài hát Latin sôi động về tình yêu và sự quyến rũ.",
    },
    {
        "id": 10,
        "title": "Hạ Còn Vương Nắng",
        "artist": "DatKaa",
        "genre": "v-pop",
        "description": "Ballad Việt về nỗi nhớ mùa hạ và tình yêu dang dở.",
    },
    {
        "id": 11,
        "title": "Blinding Lights",
        "artist": "The Weeknd",
        "genre": "synth-pop",
        "description": "Bài synth-pop về việc cảm thấy cô đơn trong thành phố về đêm.",
    },
    {
        "id": 12,
        "title": "Có Chàng Trai Viết Lên Cây",
        "artist": "Phan Mạnh Quỳnh",
        "genre": "v-pop",
        "description": "Bài ballad Việt về tình yêu thầm lặng thời học sinh.",
    },
    {
        "id": 13,
        "title": "Lạc Trôi",
        "artist": "Sơn Tùng M-TP",
        "genre": "v-pop",
        "description": "Bài hát mang âm hưởng cổ trang kết hợp hip-hop về sự cô đơn và lạc lối trong tình yêu.",
    },
    {
        "id": 14,
        "title": "Chúng Ta Của Hiện Tại",
        "artist": "Sơn Tùng M-TP",
        "genre": "v-pop",
        "description": "Bản pop R&B lãng mạn về tình yêu thanh xuân tươi đẹp nhưng đầy nuối tiếc.",
    },
    {
        "id": 15,
        "title": "Muộn Rồi Mà Sao Còn",
        "artist": "Sơn Tùng M-TP",
        "genre": "v-pop",
        "description": "Bài hát pop R&B tươi vui về cảm giác tương tư trằn trọc mất ngủ vì yêu.",
    },
    {
        "id": 16,
        "title": "Hái Sao",
        "artist": "Vũ",
        "genre": "indie",
        "description": "Bản ballad nhẹ nhàng êm dịu về tình yêu chân thành và mong muốn che chở cho người mình yêu.",
    },
    {
        "id": 17,
        "title": "Bước Qua Nhau",
        "artist": "Vũ",
        "genre": "indie",
        "description": "Bài hát indie pop hoài niệm về những ký ức mộng mơ và sự chia ly của tuổi trẻ.",
    },
    {
        "id": 18,
        "title": "Lạ Nhớ",
        "artist": "Vũ",
        "genre": "indie",
        "description": "Giai điệu nhẹ nhàng sâu lắng về nỗi nhớ tha thiết và tâm sự trầm lắng của một người đang yêu.",
    },
    {
        "id": 19,
        "title": "Nàng Thơ",
        "artist": "Hoàng Dũng",
        "genre": "ballad",
        "description": "Bài hát ballad lãng mạn, sâu lắng về hình bóng người con gái trong mộng và ký ức đẹp.",
    },
    {
        "id": 20,
        "title": "Yếu Lòng",
        "artist": "Hoàng Dũng",
        "genre": "ballad",
        "description": "Nhạc ballad cảm xúc về sự yếu đuối trong tình yêu và những tâm tư khó thổ lộ.",
    },
    {
        "id": 21,
        "title": "Thắc Mắc",
        "artist": "Thịnh Suy",
        "genre": "indie",
        "description": "Bài hát acoustic lãng mạn, đáng yêu về những trăn trở ngô nghê khi mới bắt đầu tình yêu.",
    },
    {
        "id": 22,
        "title": "Một Đêm Say",
        "artist": "Thịnh Suy",
        "genre": "indie",
        "description": "Giai điệu mộc mạc, say đắm về lời tỏ tình ngọt ngào trong cơn say.",
    },
    {
        "id": 23,
        "title": "Tháng Tư Là Lời Nói Dối Của Em",
        "artist": "Hà Anh Tuấn",
        "genre": "ballad",
        "description": "Nhạc ballad nhẹ nhàng hoài niệm về mối tình đầu trong sáng nhưng buồn thương.",
    },
    {
        "id": 24,
        "title": "Xuân Thì",
        "artist": "Hà Anh Tuấn",
        "genre": "ballad",
        "description": "Bài hát lãng mạn về vẻ đẹp thanh xuân và những hoài niệm tuổi trẻ.",
    },
    {
        "id": 25,
        "title": "Chiều Hôm Ấy",
        "artist": "JayKii",
        "genre": "ballad",
        "description": "Bản ballad đượm buồn về sự chia ly và nỗi đau khi cuộc tình kết thúc.",
    },
    {
        "id": 26,
        "title": "Ngày Chưa Bắt Đầu",
        "artist": "Anh Tú",
        "genre": "ballad",
        "description": "Nhạc ballad tha thiết về nỗi lòng đơn phương và sự hi sinh trong tình yêu.",
    },
    {
        "id": 27,
        "title": "Đã Lỡ Yêu Em Rồi",
        "artist": "JustaTee ft. Phương Ly",
        "genre": "r&b",
        "description": "Bài R&B ngọt ngào, đáng yêu về lời tỏ tình bối rối của chàng trai.",
    },
    {
        "id": 28,
        "title": "Thích Thích",
        "artist": "Phương Ly",
        "genre": "pop",
        "description": "Bài pop vui tươi, yêu đời về những rung động đầu đời ngọt ngào.",
    },
    {
        "id": 29,
        "title": "Thằng Điên",
        "artist": "JustaTee ft. Phương Ly",
        "genre": "r&b",
        "description": "Giai điệu R&B nhẹ nhàng, độc đáo về tình yêu si mê ngây dại.",
    },
    {
        "id": 30,
        "title": "Ex's Hate Me",
        "artist": "B Ray ft. Amee",
        "genre": "rap-viet",
        "description": "Bài rap pop hài hước, châm biếm về mối quan hệ với người yêu cũ.",
    },
    {
        "id": 31,
        "title": "Anh Nhà Ở Đâu Thế",
        "artist": "Amee ft. B Ray",
        "genre": "v-pop",
        "description": "Bài pop trong sáng, đáng yêu về màn thả thính ngây thơ của cô gái.",
    },
    {
        "id": 32,
        "title": "Sao Anh Chưa Về Nhà",
        "artist": "Amee",
        "genre": "v-pop",
        "description": "Nhạc pop dễ thương, hờn dỗi nhẹ nhàng khi ngóng chờ người yêu về.",
    },
    {
        "id": 33,
        "title": "Chạy Ngay Đi",
        "artist": "Sơn Tùng M-TP",
        "genre": "hip-hop",
        "description": "Bản trap hip-hop kịch tính về sự phản bội và muốn thoát khỏi mối tình độc hại.",
    },
    {
        "id": 34,
        "title": "Có Chắc Yêu Là Đây",
        "artist": "Sơn Tùng M-TP",
        "genre": "v-pop",
        "description": "Bài pop tươi sáng, ngọt ngào dành tặng người hâm mộ với thông điệp tích cực.",
    },
    {
        "id": 35,
        "title": "Ánh Nắng Của Anh",
        "artist": "Đức Phúc",
        "genre": "ballad",
        "description": "Bản ballad ngọt ngào về sự xuất hiện của người yêu làm bừng sáng cuộc đời.",
    },
    {
        "id": 36,
        "title": "Hơn Cả Yêu",
        "artist": "Đức Phúc",
        "genre": "pop",
        "description": "Bài hát pop lãng mạn thường dùng trong lễ cưới để bày tỏ tình yêu sâu sắc.",
    },
    {
        "id": 37,
        "title": "Ngày Đầu Tiên",
        "artist": "Đức Phúc",
        "genre": "pop",
        "description": "Bài pop lãng mạn ấm áp về ngày cầu hôn và sự bắt đầu một chặng đường mới.",
    },
    {
        "id": 38,
        "title": "Giữ Lấy Làm Gì",
        "artist": "Monstar",
        "genre": "r&b",
        "description": "Nhạc R&B hiện đại về việc buông tay trong tình yêu để cả hai bớt tổn thương.",
    },
    {
        "id": 39,
        "title": "Có Em Đời Vẫn Vui",
        "artist": "Chillies",
        "genre": "indie",
        "description": "Bản indie pop năng động, lạc quan về niềm hạnh phúc khi có người yêu đồng hành.",
    },
    {
        "id": 40,
        "title": "Vùng Ký Ức",
        "artist": "Chillies",
        "genre": "indie",
        "description": "Nhạc indie rock cảm xúc về những hoài niệm quá khứ và dấu vết tuổi trẻ.",
    },
    {
        "id": 41,
        "title": "Mascara",
        "artist": "Chillies",
        "genre": "indie",
        "description": "Bài hát indie trầm buồn về nỗi đau giọt nước mắt lăn trên má người con gái.",
    },
    {
        "id": 42,
        "title": "Chưa Quên Người Yêu Cũ",
        "artist": "Hà Nhi",
        "genre": "ballad",
        "description": "Nhạc ballad da diết về sự giằng xé khi chưa thể quên đi hình bóng cũ.",
    },
    {
        "id": 43,
        "title": "Ngày Mai Người Ta Lấy Chồng",
        "artist": "Thành Đạt",
        "genre": "ballad",
        "description": "Nhạc ballad xót xa về nỗi đau nhìn người mình yêu đi lấy chồng.",
    },
    {
        "id": 44,
        "title": "Cát Bụi",
        "artist": "Trịnh Công Sơn",
        "genre": "trinh-music",
        "description": "Nhạc Trịnh triết lý về kiếp nhân sinh, sự hữu hạn của đời người và hư vô.",
    },
    {
        "id": 45,
        "title": "Diễm Xưa",
        "artist": "Trịnh Công Sơn",
        "genre": "trinh-music",
        "description": "Nhạc Trịnh hoài niệm, lãng mạn về cơn mưa chiều và hình bóng người thiếu nữ.",
    },
    {
        "id": 46,
        "title": "Để Mị Nói Cho Mà Nghe",
        "artist": "Hoàng Thùy Linh",
        "genre": "folk-pop",
        "description": "Nhạc dân gian đương đại sôi động về sự tự do và vươn lên của người phụ nữ.",
    },
    {
        "id": 47,
        "title": "Gieo Quẻ",
        "artist": "Hoàng Thùy Linh ft. Đen Vâu",
        "genre": "folk-pop",
        "description": "Sự kết hợp dân gian đương đại và rap về ước nguyện may mắn đầu năm.",
    },
    {
        "id": 48,
        "title": "Trốn Tìm",
        "artist": "Đen Vâu ft. MTV",
        "genre": "rap-viet",
        "description": "Bài rap hoài niệm sâu lắng về sự trưởng thành và trò chơi trốn tìm tuổi thơ.",
    },
    {
        "id": 49,
        "title": "Đi Về Nhà",
        "artist": "Đen Vâu ft. JustaTee",
        "genre": "rap-viet",
        "description": "Bài rap ấm áp về tình cảm gia đình và sự bình yên khi trở về nhà.",
    },
    {
        "id": 50,
        "title": "Mang Tiền Về Cho Mẹ",
        "artist": "Đen Vâu ft. Nguyên Thảo",
        "genre": "rap-viet",
        "description": "Bài rap ý nghĩa về lòng hiếu thảo và sự trân trọng sự vất vả của cha mẹ.",
    },
    {
        "id": 51,
        "title": "Rolling in the Deep",
        "artist": "Adele",
        "genre": "pop",
        "description": "Bài hát pop soul mạnh mẽ về sự giận giữ và đáp trả sau khi bị phản bội.",
    },
    {
        "id": 52,
        "title": "Easy On Me",
        "artist": "Adele",
        "genre": "ballad",
        "description": "Nhạc ballad cảm xúc về sự tha thứ và hành trình chữa lành sau đổ vỡ hôn nhân.",
    },
    {
        "id": 53,
        "title": "Hotel California",
        "artist": "Eagles",
        "genre": "rock",
        "description": "Bản rock kinh điển với tiếng guitar huyền thoại về sự xa hoa và bẫy rập cuộc sống.",
    },
    {
        "id": 54,
        "title": "Take Me to Church",
        "artist": "Hozier",
        "genre": "indie",
        "description": "Bài hát indie rock sâu sắc về tình yêu, niềm tin và sự tự do cá nhân.",
    },
    {
        "id": 55,
        "title": "Counting Stars",
        "artist": "OneRepublic",
        "genre": "pop-rock",
        "description": "Bản pop rock sôi động về khát vọng vượt qua áp lực tài chính để sống với ước mơ.",
    },
    {
        "id": 56,
        "title": "Viva La Vida",
        "artist": "Coldplay",
        "genre": "alternative",
        "description": "Nhạc rock nghệ thuật hoành tráng về sự sụp đổ của các đế chế và quyền lực.",
    },
    {
        "id": 57,
        "title": "Yellow",
        "artist": "Coldplay",
        "genre": "alternative",
        "description": "Bản rock ngọt ngào, lãng mạn tôn vinh vẻ đẹp thuần khiết của người yêu.",
    },
    {
        "id": 58,
        "title": "Perfect",
        "artist": "Ed Sheeran",
        "genre": "ballad",
        "description": "Bản ballad lãng mạn tuyệt vời dành cho các cặp đôi và lễ cưới.",
    },
    {
        "id": 59,
        "title": "Thinking Out Loud",
        "artist": "Ed Sheeran",
        "genre": "pop",
        "description": "Bài hát tình yêu vượt thời gian về sự gắn kết trọn đời đến khi về già.",
    },
    {
        "id": 60,
        "title": "Memories",
        "artist": "Maroon 5",
        "genre": "pop",
        "description": "Bài pop nhẹ nhàng hoài niệm dành tưởng nhớ những người thân yêu đã xa.",
    },
    {
        "id": 61,
        "title": "Sugar",
        "artist": "Maroon 5",
        "genre": "pop",
        "description": "Nhạc pop vui tươi, sôi động về sự ngọt ngào của tình yêu.",
    },
    {
        "id": 62,
        "title": "Payphone",
        "artist": "Maroon 5 ft. Wiz Khalifa",
        "genre": "pop",
        "description": "Nhạc pop bắt tai về sự hối tiếc và nuối tiếc mối tình đã qua.",
    },
    {
        "id": 63,
        "title": "Uptown Funk",
        "artist": "Mark Ronson ft. Bruno Mars",
        "genre": "pop",
        "description": "Giai điệu funk sôi động, tràn đầy năng lượng nhảy múa.",
    },
    {
        "id": 64,
        "title": "Just the Way You Are",
        "artist": "Bruno Mars",
        "genre": "pop",
        "description": "Nhạc pop ca ngợi vẻ đẹp tự nhiên và sự hoàn hảo của người yêu.",
    },
    {
        "id": 65,
        "title": "Leave The Door Open",
        "artist": "Silk Sonic (Bruno Mars, Anderson .Paak)",
        "genre": "r&b",
        "description": "Nhạc R&B cổ điển sang trọng, quyến rũ và đầy lãng mạn.",
    },
    {
        "id": 66,
        "title": "Stay",
        "artist": "The Kid LAROI & Justin Bieber",
        "genre": "pop",
        "description": "Bài pop nhịp điệu nhanh về lời cầu xin người yêu ở lại.",
    },
    {
        "id": 67,
        "title": "Love Yourself",
        "artist": "Justin Bieber",
        "genre": "pop",
        "description": "Bài pop acoustic nhẹ nhàng châm biếm về việc tự yêu bản thân sau khi chia tay.",
    },
    {
        "id": 68,
        "title": "Sorry",
        "artist": "Justin Bieber",
        "genre": "pop",
        "description": "Nhạc dance pop sôi động xin lỗi và mong muốn làm lại từ đầu.",
    },
    {
        "id": 69,
        "title": "Bad Guy",
        "artist": "Billie Eilish",
        "genre": "pop",
        "description": "Nhạc electropop cá tính, độc đáo và đầy phong cách phá cách.",
    },
    {
        "id": 70,
        "title": "Ocean Eyes",
        "artist": "Billie Eilish",
        "genre": "indie",
        "description": "Bản indie pop huyền bí, dịu êm về đôi mắt sâu thẳm như đại dương.",
    },
    {
        "id": 71,
        "title": "Drivers License",
        "artist": "Olivia Rodrigo",
        "genre": "ballad",
        "description": "Bài pop ballad u buồn về cảm giác đau đớn khi thất tình tuổi mới lớn.",
    },
    {
        "id": 72,
        "title": "Good 4 U",
        "artist": "Olivia Rodrigo",
        "genre": "rock",
        "description": "Bản pop punk bùng nổ, mạnh mẽ mỉa mai người yêu cũ mau chóng quên mình.",
    },
    {
        "id": 73,
        "title": "As It Was",
        "artist": "Harry Styles",
        "genre": "synth-pop",
        "description": "Nhạc synth pop bắt tai về sự thay đổi của cuộc sống và sự cô đơn.",
    },
    {
        "id": 74,
        "title": "Watermelon Sugar",
        "artist": "Harry Styles",
        "genre": "pop",
        "description": "Nhạc pop mùa hè tươi vui, sảng khoái và ngọt ngào.",
    },
    {
        "id": 75,
        "title": "Dynamite",
        "artist": "BTS",
        "genre": "k-pop",
        "description": "Nhạc disco pop năng động tiếng Anh, lan tỏa năng lượng tích cực và niềm vui.",
    },
    {
        "id": 76,
        "title": "Butter",
        "artist": "BTS",
        "genre": "k-pop",
        "description": "Bài dance pop mịn màng, quyến rũ với nhịp điệu cực kỳ cuốn hút.",
    },
    {
        "id": 77,
        "title": "Spring Day",
        "artist": "BTS",
        "genre": "k-pop",
        "description": "Bản ballad K-Pop sâu lắng về nỗi nhớ bạn bè và hy vọng mùa xuân trở lại.",
    },
    {
        "id": 78,
        "title": "Gangnam Style",
        "artist": "PSY",
        "genre": "k-pop",
        "description": "Bản dance K-Pop bùng nổ toàn cầu với điệu nhảy ngựa huyền thoại.",
    },
    {
        "id": 79,
        "title": "Kill This Love",
        "artist": "BLACKPINK",
        "genre": "k-pop",
        "description": "Nhạc K-Pop mạnh mẽ, cá tính về quyết tâm chấm dứt một tình yêu độc hại.",
    },
    {
        "id": 80,
        "title": "DDU-DU DDU-DU",
        "artist": "BLACKPINK",
        "genre": "k-pop",
        "description": "Nhạc K-Pop hip-hop thời thượng thể hiện sự tự tin và sức mạnh nữ quyền.",
    },
    {
        "id": 81,
        "title": "How You Like That",
        "artist": "BLACKPINK",
        "genre": "k-pop",
        "description": "Nhạc K-Pop sôi động về việc vượt qua khó khăn để trỗi dậy mạnh mẽ.",
    },
    {
        "id": 82,
        "title": "Flower",
        "artist": "JISOO",
        "genre": "k-pop",
        "description": "Bài hát pop K-Pop mang giai điệu truyền thống quyến rũ về sự buông bỏ tình yêu.",
    },
    {
        "id": 83,
        "title": "Hype Boy",
        "artist": "NewJeans",
        "genre": "k-pop",
        "description": "Nhạc pop R&B tươi mới, tràn đầy sức sống tuổi trẻ thế hệ mới.",
    },
    {
        "id": 84,
        "title": "Super Shy",
        "artist": "NewJeans",
        "genre": "k-pop",
        "description": "Nhạc UK garage/Jersey club dễ thương về sự ngượng ngùng khi đối diện người mình thích.",
    },
    {
        "id": 85,
        "title": "Ditto",
        "artist": "NewJeans",
        "genre": "k-pop",
        "description": "Bản hoài niệm mộng mơ về mối tình đầu tuổi học trò.",
    },
    {
        "id": 86,
        "title": "Night Dancer",
        "artist": "Imase",
        "genre": "j-pop",
        "description": "Bản J-Pop funk sôi động gây sốt toàn cầu với nhịp điệu cuốn hút để nhảy múa.",
    },
    {
        "id": 87,
        "title": "First Love",
        "artist": "Utada Hikaru",
        "genre": "j-pop",
        "description": "Bản ballad J-Pop kinh điển về kỷ niệm đẹp và nỗi buồn mối tình đầu.",
    },
    {
        "id": 88,
        "title": "Lemon",
        "artist": "Kenshi Yonezu",
        "genre": "j-pop",
        "description": "Nhạc J-Pop sâu lắng về nỗi đau mất mát người thân yêu và sự chữa lành.",
    },
    {
        "id": 89,
        "title": "Idol",
        "artist": "YOASOBI",
        "genre": "j-pop",
        "description": "Nhạc J-Pop tốc độ nhanh, hấp dẫn về thế giới rực rỡ và góc khuất của thần tượng.",
    },
    {
        "id": 90,
        "title": "Yoru ni Kakeru",
        "artist": "YOASOBI",
        "genre": "j-pop",
        "description": "Giai điệu J-Pop bắt tai trên nền câu chuyện tâm lý u buồn.",
    },
    {
        "id": 91,
        "title": "Until I Found You",
        "artist": "Stephen Sanchez",
        "genre": "pop",
        "description": "Nhạc retro pop lãng mạn mang phong cách thập niên 50 cổ điển.",
    },
    {
        "id": 92,
        "title": "Heat Waves",
        "artist": "Glass Animals",
        "genre": "indie",
        "description": "Nhạc indie pop bay bổng về ký ức về người yêu cũ vào những đêm hè.",
    },
    {
        "id": 93,
        "title": "Starboy",
        "artist": "The Weeknd ft. Daft Punk",
        "genre": "r&b",
        "description": "Bài R&B electropop nói về lối sống thượng lưu và danh vọng.",
    },
    {
        "id": 94,
        "title": "Save Your Tears",
        "artist": "The Weeknd",
        "genre": "synth-pop",
        "description": "Nhạc synth-pop hoài niệm thập niên 80 về sự hối hận khi làm tổn thương người khác.",
    },
    {
        "id": 95,
        "title": "Sunflower",
        "artist": "Post Malone, Swae Lee",
        "genre": "hip-hop",
        "description": "Nhạc hip-hop pop tươi sáng trong phim Spider-Man về tình yêu kiên trì.",
    },
    {
        "id": 96,
        "title": "Circles",
        "artist": "Post Malone",
        "genre": "pop",
        "description": "Nhạc pop rock nhẹ nhàng về vòng lặp quẩn quanh của một mối quan hệ sắp tan vỡ.",
    },
    {
        "id": 97,
        "title": "Shallow",
        "artist": "Lady Gaga, Bradley Cooper",
        "genre": "ballad",
        "description": "Bản song ca bùng nổ cảm xúc về việc lao mình vào tình yêu sâu đậm.",
    },
    {
        "id": 98,
        "title": "Radioactive",
        "artist": "Imagine Dragons",
        "genre": "rock",
        "description": "Bản alternative rock mạnh mẽ về sự thức tỉnh và nguồn năng lượng mới.",
    },
    {
        "id": 99,
        "title": "Demons",
        "artist": "Imagine Dragons",
        "genre": "rock",
        "description": "Bản rock lắng đọng về những góc tối và con quỷ trong tâm hồn mỗi người.",
    },
    {
        "id": 100,
        "title": "Believer",
        "artist": "Imagine Dragons",
        "genre": "rock",
        "description": "Nhạc rock truyền cảm hứng mạnh mẽ về việc biến nỗi đau thành sức mạnh.",
    },
]

def song_to_passage(song: dict) -> str:
    return f"Bài hát: {song['title']}. Nghệ sĩ: {song['artist']}. Thể loại: {song['genre']}. {song['description']}"
